version: "3.8" # версия вашего docker-compose
services: # имеджи, которые запустятся по вашему желанию
  db: # название моего имеджа
    image: postgres:latest # скачает image postgres 12 версии
    volumes: # часть настроек для хранения данных, пока для нас это не важно
      - type: volume
        source: postgresdb-data
        target: /var/lib/postgresql/data
    ports: # порты
      - "5433:5432"
    environment: # переменные окружения, меняйте их если хотите поменять пароль, логин или название стартовой базы данных
      POSTGRES_USER: postgres
      POSTGRES_DB: space
      POSTGRES_PASSWORD: 1234
    networks:
      - app_network
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: kabanets
      MINIO_SECRET_KEY: vovakrutoi
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-data:/data
    command: server /data
  redis:
    image: redis:latest #Ц383ОЕ 190
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass rip
    volumes:
      - redis-data:/data
networks:
  app_network:
    driver: bridge
volumes: # часть настроек для хранения данных
  postgresdb-data:
    driver: local
  minio-data:
    driver: local
  redis-data:
    driver: local
