package model

const (
	PLANET_STATUS_ACTIVE  = "активна"
	PLANET_STATUS_DELETED = "удалена"

	CONSTELLATION_STATUS_DRAFT     = "created"
	CONSTELLATION_STATUS_WORK      = "inprogress"
	CONSTELLATION_STATUS_COMPLETED = "completed"
	CONSTELLATION_STATUS_REJECTED  = "canceled"
	CONSTELLATION_STATUS_DELETED   = "deleted"
)
