// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/planet": {
            "get": {
                "description": "Возращает список всех активных планетаей",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Получение списка планеты",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код планеты",
                        "name": "searchCode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планетаей",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    }
                }
            }
        },
        "/planet/create": {
            "post": {
                "description": "Создает новый планета с предоставленными данными",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Создание нового планеты",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код планеты",
                        "name": "searchCode",
                        "in": "query"
                    },
                    {
                        "description": "Пользовательский объект в формате JSON",
                        "name": "planet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PlanetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планетаей",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}": {
            "get": {
                "description": "Возвращает информацию о планетае по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Получение планеты по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планеты",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о планетае",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}/delete": {
            "delete": {
                "description": "Удаляет планета по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Удаление планеты",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планеты",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код планеты",
                        "name": "searchCode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планетаей",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}/constellation": {
            "post": {
                "description": "Добавляет планета к доставке по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Добавление планеты к доставке",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планеты",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код планеты",
                        "name": "searchCode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планетаей",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}/image": {
            "post": {
                "description": "Добавляет изображение к планетау по его ID",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Добавление изображения к планетау",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планеты",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Изображение планеты",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}/update": {
            "put": {
                "description": "Обновляет информацию о планетае по его ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Обновление информации о планетае",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планеты",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о планетае",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    }
                }
            }
        },
        "/planets/{planet_id}/constellation": {
            "post": {
                "description": "Удаляет планета из созвездия по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Удаление планеты из созвездия",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планеты",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код планеты",
                        "name": "searchCode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планетаей",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    }
                }
            }
        },
        "/constellation": {
            "get": {
                "description": "Возвращает список всех не удаленных доставок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Получение списка доставок",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Номер рейса",
                        "name": "searchFlightNumber",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Начало даты формирования",
                        "name": "startFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Конец даты формирования",
                        "name": "endFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Статус созвездия",
                        "name": "constellationStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список доставок",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationRequest"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationRequest"
                        }
                    }
                }
            }
        },
        "/constellation/{id}": {
            "get": {
                "description": "Возвращает информацию о доставке по её идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Получение созвездия по идентификатору",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор созвездия",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о доставке",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "400": {
                        "description": "Недопустимый идентификатор созвездия",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    }
                }
            }
        },
        "/constellation/{id}/delete": {
            "delete": {
                "description": "Удаляет доставку по её идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Удаление созвездия",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор созвездия",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Номер рейса",
                        "name": "searchFlightNumber",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Начало даты формирования",
                        "name": "startFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Конец даты формирования",
                        "name": "endFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Статус созвездия",
                        "name": "constellationStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планетаей",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationRequest"
                        }
                    },
                    "400": {
                        "description": "Недопустимый идентификатор созвездия",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationRequest"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationRequest"
                        }
                    }
                }
            }
        },
        "/constellation/{id}/status": {
            "put": {
                "description": "Обновляет статус созвездия для модератора по идентификатору созвездия",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Обновление статуса созвездия для модератора",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор созвездия",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус созвездия",
                        "name": "constellationStatus",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationUpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о доставке",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "400": {
                        "description": "Недопустимый идентификатор созвездия или ошибка чтения JSON объекта",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    }
                }
            }
        },
        "/constellation/{id}/update": {
            "put": {
                "description": "Обновляет номер рейса для созвездия по её идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Обновление номера рейса созвездия",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор созвездия",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый номер рейса",
                        "name": "flightNumber",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationUpdateFlightNumberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о доставке",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "400": {
                        "description": "Недопустимый идентификатор созвездия или ошибка чтения JSON объекта",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    }
                }
            }
        },
        "/constellation/{id}/user": {
            "put": {
                "description": "Обновляет статус созвездия для пользователя по идентификатору созвездия",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Обновление статуса созвездия для пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор созвездия",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о доставке",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "400": {
                        "description": "Недопустимый идентификатор созвездия",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    }
                }
            }
        },
        "/user/": {
            "get": {
                "description": "Получение данных пользователя по его идентификатору",
                "produces": [
                    "application/json"
                ],
                "summary": "Получить пользователя по идентификатору",
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Авторизация пользователя и генерация JWT-токена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Вход пользователя",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "description": "Выход пользователя из системы и удаление токена из куков",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Выход пользователя",
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/refreshtoken": {
            "post": {
                "description": "Обновление пары токенов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Обновление токенов",
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Регистрация нового пользователя с предоставленной информацией.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Регистрация нового пользователя.",
                "parameters": [
                    {
                        "description": "Пользовательский объект в формате JSON",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешно зарегистрированный пользователь",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.User"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Planet": {
            "type": "object",
            "properties": {
                "airline": {
                    "type": "string",
                    "example": "AirlineX"
                },
                "planet_code": {
                    "type": "string",
                    "example": "ABC123"
                },
                "planet_id": {
                    "type": "integer"
                },
                "planet_status": {
                    "type": "string",
                    "example": "checked"
                },
                "planet_type": {
                    "type": "string",
                    "example": "suitcase"
                },
                "owner_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "pasport_details": {
                    "type": "string",
                    "example": "123456789"
                },
                "photo": {
                    "type": "string",
                    "example": "http://example.com/planet.jpg"
                },
                "size": {
                    "type": "string",
                    "example": "large"
                },
                "weight": {
                    "type": "number",
                    "example": 23.5
                }
            }
        },
        "model.PlanetRequest": {
            "type": "object",
            "properties": {
                "airline": {
                    "type": "string",
                    "example": "AirlineX"
                },
                "planet_code": {
                    "type": "string",
                    "example": "ABC123"
                },
                "planet_type": {
                    "type": "string",
                    "example": "suitcase"
                },
                "owner_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "pasport_details": {
                    "type": "string",
                    "example": "123456789"
                },
                "size": {
                    "type": "string",
                    "example": "large"
                },
                "weight": {
                    "type": "number",
                    "example": 23.5
                }
            }
        },
        "model.PlanetsGetResponse": {
            "type": "object",
            "properties": {
                "planets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Planet"
                    }
                },
                "constellation_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.ConstellationGetResponse": {
            "type": "object",
            "properties": {
                "planets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Planet"
                    }
                },
                "confirmation_date": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "constellation_id": {
                    "type": "integer"
                },
                "constellation_status": {
                    "type": "string"
                },
                "flight_number": {
                    "type": "string"
                },
                "formation_date": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "model.ConstellationRequest": {
            "type": "object",
            "properties": {
                "confirmation_date": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "constellation_id": {
                    "type": "integer"
                },
                "constellation_status": {
                    "type": "string"
                },
                "flight_number": {
                    "type": "string"
                },
                "formation_date": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "model.ConstellationUpdateFlightNumberRequest": {
            "type": "object",
            "properties": {
                "flight_number": {
                    "type": "string"
                }
            }
        },
        "model.ConstellationUpdateStatusRequest": {
            "type": "object",
            "properties": {
                "constellation_status": {
                    "type": "string"
                }
            }
        },
        "model.Role": {
            "type": "string",
            "enum": [
                "пользователь",
                "модератор"
            ],
            "x-enum-varnames": [
                "UserRole",
                "ModeratorRole"
            ]
        },
        "model.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.Role"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.UserLoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.UserRegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
