// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/constellation": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список всех не удаленных созвездий",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Получение списка созвездий",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Начало даты формирования",
                        "name": "startFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Конец даты формирования",
                        "name": "endFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Статус созвездия",
                        "name": "constellationStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список созвездий",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationRequest"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/constellation/{constellation_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию о созвездии по её идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Получение созвездия по идентификатору",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор созвездия",
                        "name": "constellation_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о созвездии",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/constellation/{constellation_id}/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет доставку по её идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Удаление созвездия",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор созвездия",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Начало даты формирования",
                        "name": "startFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Конец даты формирования",
                        "name": "endFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Статус созвездия",
                        "name": "constellationStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список багажей",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationRequest"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/constellation/{constellation_id}/status/moderator": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет статус чернового созвездия для юзера и обновляет статус созвездия по идентификатору созвездия и новому статусу для модератора",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Обновление статуса созвездия",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор созвездия",
                        "name": "constellation_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус созвездия",
                        "name": "constellationStatus",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationUpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о созвездии",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/constellation/{constellation_id}/update": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет поля созвездия по её идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Созвездие"
                ],
                "summary": "Обновление созвездие",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор созвездия",
                        "name": "constellation_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новое созвездие",
                        "name": "newConstellation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о созвездии",
                        "schema": {
                            "$ref": "#/definitions/model.ConstellationGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/planet": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возращает список всех активных планет и ид черновой заявки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Получение списка планет",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Название планеты",
                        "name": "searchName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планет",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/planet/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создает новый планета с предоставленными данными",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Создание нового планетаа",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код планетаа",
                        "name": "searchCode",
                        "in": "query"
                    },
                    {
                        "description": "Пользовательский объект в формате JSON",
                        "name": "planet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PlanetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планетаей",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "У пользователя нет прав для этого запроса",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию о планете по ее ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Получение планеты по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планетаа",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о планетае",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}/constellation": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавляет планету к созвездию по ее ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Добавление планеты к созвездии",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планеты",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код планеты",
                        "name": "searchName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планет",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет планета из созвездия по еe ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Удаление планеты из созвездия",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планеты",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код планеты",
                        "name": "searchName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планет",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет планету по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Удаление планеты",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планетаа",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Название планеты",
                        "name": "searchName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список планет",
                        "schema": {
                            "$ref": "#/definitions/model.PlanetsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "У пользователя нет прав для этого запроса",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}/image": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавляет изображение к планете по ее ID",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Добавление изображения к планете",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планета",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Изображение планеты",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о планете с изображением",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "У пользователя нет прав для этого запроса",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/planet/{planet_id}/update": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет информацию о планетe по его ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Планета"
                ],
                "summary": "Обновление информации о планетe",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID планеты",
                        "name": "planet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о планетe",
                        "schema": {
                            "$ref": "#/definitions/model.Planet"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "У пользователя нет прав для этого запроса",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Авторизация пользователя и генерация JWT-токена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Вход пользователя",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токен",
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Выход пользователя из системы и удаление токена из куков",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Выход пользователя",
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Регистрация нового пользователя с предоставленной информацией.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Регистрация нового пользователя.",
                "parameters": [
                    {
                        "description": "Пользовательский объект в формате JSON",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токен",
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ConstellationGetResponse": {
            "type": "object",
            "properties": {
                "confirmation_date": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "formation_date": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "planets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PlanetInConstellation"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.ConstellationRequest": {
            "type": "object",
            "properties": {
                "confirmation_date": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "formation_date": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.ConstellationUpdateRequest": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "model.ConstellationUpdateStatusRequest": {
            "type": "object",
            "properties": {
                "constellationStatus": {
                    "type": "string"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "model.Planet": {
            "type": "object",
            "properties": {
                "color1": {
                    "type": "string",
                    "example": "#ababab"
                },
                "color2": {
                    "type": "string",
                    "example": "#8a8a8a"
                },
                "discovered": {
                    "type": "string",
                    "example": "Неизвестно"
                },
                "distance": {
                    "type": "string",
                    "example": "Неизвестно"
                },
                "imageName": {
                    "type": "string",
                    "example": "http://example.com/mars.jpg"
                },
                "info": {
                    "type": "string",
                    "example": "Неизвестно"
                },
                "mass": {
                    "type": "string",
                    "example": "Неизвестно"
                },
                "name": {
                    "type": "string",
                    "example": "Планета"
                },
                "planetId": {
                    "type": "integer"
                },
                "status": {
                    "type": "string",
                    "example": "активна"
                }
            }
        },
        "model.PlanetInConstellation": {
            "type": "object",
            "properties": {
                "color1": {
                    "type": "string",
                    "example": "#ababab"
                },
                "color2": {
                    "type": "string",
                    "example": "#8a8a8a"
                },
                "id": {
                    "type": "string"
                },
                "imageName": {
                    "type": "string",
                    "example": "http://example.com/mars.jpg"
                },
                "name": {
                    "type": "string",
                    "example": "Планета"
                }
            }
        },
        "model.PlanetRequest": {
            "type": "object",
            "properties": {
                "color1": {
                    "type": "string",
                    "example": "#ababab"
                },
                "color2": {
                    "type": "string",
                    "example": "#8a8a8a"
                },
                "discovered": {
                    "type": "string",
                    "example": "Неизвестно"
                },
                "distance": {
                    "type": "string",
                    "example": "Неизвестно"
                },
                "info": {
                    "type": "string",
                    "example": "Неизвестно"
                },
                "mass": {
                    "type": "string",
                    "example": "Неизвестно"
                },
                "name": {
                    "type": "string",
                    "example": "Планета"
                }
            }
        },
        "model.PlanetsGetResponse": {
            "type": "object",
            "properties": {
                "constellationId": {
                    "type": "integer",
                    "example": 1
                },
                "planets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Planet"
                    }
                }
            }
        },
        "model.Role": {
            "type": "string",
            "enum": [
                "пользователь",
                "модератор"
            ],
            "x-enum-varnames": [
                "UserRole",
                "ModeratorRole"
            ]
        },
        "model.UserLoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.UserLoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.Role"
                }
            }
        },
        "model.UserRegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BagTracker RestAPI",
	Description:      "API server for Space application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
